### ISSUE TITLE
Abilty to import/export "channel <-> stream" information from the souce.db

### ISSUE THREAD

**Issue by Mike-KL** [primaeval/script.tvguide.fullscreen#1]
Not quite sure what I am asking for, but I do know that if I have a number of devices around the home running Kodi, I don't want to keep manually creating relationships between Channels in my TV Guide and the add-on/link providing the preferred stream.

Assuming all devices have access to same tvguide.xml, and device have same addons/links to preferred streaming method is it as simple as copying the sources.db?

Thanks for re-awaking my interest in using TV Guide to provide my own EPG of preferred channels which can be played back via my preferred addon/link stream.  Really happy with these developments primaeval 👍👍👍

**Comment by primaeval** [comment]
Try http://sqlitebrowser.org/ to have a look inside the sources.db file and check the paths.

The channel mapping is in the sources.db. All the added addon folders end up in addons.ini and the categories in categories.ini. 

If they are the same just copy the addon_data folder over to the new box.

If you have slightly different setups around the house I would just add the addons.ini and categories.ini and then find the best channels again when you try to play them.

**Comment by Mike-KL** [comment]
@primaeval Thanks already have sqlitebrowser installed on PC and quickly checked sources.db and can clearly see relevant information within channels and custom_stream_url tables etc.

Excellent if I its a simple as copy over contents of Userdata\addon_data\script.tvguide.fullscreen from one device to another. (When devices already have same addons, dont intend to do this often, but good to know)
