### ISSUE TITLE
Autoplay Stopped Working

### ISSUE THREAD

**Issue by jonjo40** [primaeval/script.tvguide.fullscreen#102]
Hey guys, loving what you are doing with this. Love it. Don't know if Im allowed to submit an issue but, I can't figure it out.

Ever since (I noticed) the VPN menu appeared, The autoplays has stopped working. I dont suggest its related at all but, is more for a timing of when it stopped working for me. Do you know about this or could I have messed up?

When Im expecting an autoplay reminder to trigger, I get a Kodi error popup (bottom right) saying check the event log but, there is never anything in there that I can see.

Kodi 16.1 | Windows 7 | Using The awesome White snow skin

 Thanks guys. :)

**Comment by primaeval** [comment]
Thanks. I expect it was when the VPN code was added. I'll have a look.
Is it happening to every type of url: addons and direct http links?

**Comment by jonjo40** [comment]
I only use it for one type of url and its for a another Kodi addon like 

plugin://plugin.video.myfirstaddon/?url=287&mode=2&name=BBC1

**Comment by primaeval** [comment]
Are you using it through the vpn? The default Settings \ VPN have it turned on. 
Does it work if you turn those off?

**Comment by jonjo40** [comment]
Its not a VPN no. The choices in the VPN settings window is actually grey'd out - like not selectable / clickable. I've never touched them anyways though.

**Comment by primaeval** [comment]
Try 0.0.333. The vpn setting had a default of on and was hidden. The code failed because the vpn addon wasn't installed. It seems to work ok for me now with the fix.

@Zomboided Could you check this fix please. It really needs something more robust that an except to enable the vpn behaviour.

**Comment by jonjo40** [comment]
Thank you. :) I'll give it a go.

**Comment by primaeval** [comment]
To test AutoPlay without waiting for the next program to start you can uncomment these 2 lines. ie remove the "#"
https://github.com/primaeval/script.tvguide.fullscreen/blob/master/autoplay.py#L60
https://github.com/primaeval/script.tvguide.fullscreen/blob/master/autoplay.py#L67

**Comment by primaeval** [comment]
The test will play immediately and stop 1 minute after that if all goes well.

**Comment by Zomboided** [comment]
Sorry about that...checked the code around it not being installed in gui.py before copying it into play.py and playwith.py.  Added a check to see if vpn mgr is installed before trying to do anything (or relying on exceptions) and reverted VPN defaults (also behind the same check)

**Comment by jonjo40** [comment]
Still not working for me. Wait, do I have to install the service.vpn.manager now before it will work again? I'm getting confused.

**Comment by primaeval** [comment]
It should just work for you no matter if vpn manager is installed or not. Is there still an error in the kodi.log file about an exception when it tries to play?

**Comment by jonjo40** [comment]
No. the popup error has gone now but, it just doesn't start it anymore. In my Kodi events, it has the alarm clock things but, they don't switch it on anymore. :(

**Comment by primaeval** [comment]
I think I better have a look at your kodi.log. You can send it to primaeval.dev AT gmail DOT com if it contains anything you don't want made public.

**Comment by jonjo40** [comment]
Fantastic. Thank you so much. I'll run it again and after it "hasn't" switched, I'll give you the log. :)

**Comment by primaeval** [comment]
Don't forget to uncomment those test lines unless you want to wait.

**Comment by jonjo40** [comment]
Ive tried both. no luck.

**Comment by primaeval** [comment]
Turn on debug logging. Restart Kodi. Try again and send me the kodi.log file.

**Comment by jonjo40** [comment]
ok. Thank you again

**Comment by jonjo40** [comment]
Sent email

**Comment by Zomboided** [comment]
Prmaeval, forward it to me if I'm causing this

**Comment by primaeval** [comment]
@jonjo40 Nothing has come through yet.

**Comment by jonjo40** [comment]
sent again (but, I had the correct address)

**Comment by primaeval** [comment]
It ended up in spam. What have you been up to in the past? ;)

**Comment by jonjo40** [comment]
I dont understand

**Comment by primaeval** [comment]
Maybe there have been lots of spammers from your email domain. I just saw one from ffmpeg.org there too. That wasn't spam either.

**Comment by jonjo40** [comment]
oooh, yeah its a freebie email account. Probably gets abused to all hell. :D

**Comment by primaeval** [comment]
It runs the play.py function ok but I can't see it trying to play anything.
Did it used to work on the channel you tried?
Does the channel play ok from the epg?
Send me a link to the stream by email if you can.

**Comment by jonjo40** [comment]
damn. Its a premium and (not very legal) streaming service, if you know what I mean? Is there anyway I can go back to before the VPN thing appeared? It worked great then.

**Comment by primaeval** [comment]
You can manually go back to 0.0.329 today. Make sure you turn off automatic update for TV Guide Fullscreen first. Then manually install this https://github.com/primaeval/script.tvguide.fullscreen/files/914499/script.tvguide.fullscreen-0.0.329.zip
I'll have a look at the code again tomorrow when I'm fresh. Do you mind me forwarding the log to Zomboided?

**Comment by jonjo40** [comment]
Thank you so much and of course not, whatever is best. Send away. Thanks to all you guys. :)

**Comment by primaeval** [comment]
0.0.334 should fix it but then again 0.0.333 should have worked too.

**Comment by jonjo40** [comment]
Thank you!!!!!!!! I've updated to the latest and everything is working again. Fantastic. Thanks very much :)
