### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by eric859** [primaeval/script.tvguide.fullscreen#109]
People typically watch the same stations on a regular basis.  I would like to respectfully offer a feature idea to have the addon automaticlly sort most used channels to the top of the EPG window.  I believe this would be a great feature to add to the software to make it even more useful.  If this is not the area to post feaure requests, please let me know and I'll try to move it elsewhere.

**Comment by primaeval** [comment]
It's usually best to put these sort of posts in the forum and leave the Issues for really broken things but especially when other users might have some insight. It is mostly me that reads the stuff here.

Anyway, you can reorder the channels however you like in Menu\Channels. You can set up Channel Categories with just your favourites in. Or you can make your own xmltv file with Webgrab+Plus and order it in any way you like.
