### ISSUE TITLE
black background on aeon nox skin!

### ISSUE THREAD

**Issue by bugatsinho** [primaeval/script.tvguide.fullscreen#112]
any ideas why in aeon nox skin the tvguide has black background whatever skin theme i select?

**Comment by primaeval** [comment]
No. Sometimes things are missing when the surface codec is turned on in Kodi\Settings\System\Video.

**Comment by bugatsinho** [comment]
i noticed tho that the tv guide skin has 720p folders.Aeon nox is a 1080i skin.do you think it will be a trick for that so to fix the issue?

**Comment by primaeval** [comment]
I just tried a fresh install of Kodi 17.6, TVGF 0.17.379 and the latest Aeon Nox from Kodi on Win7 32bit. The default background is fine. What are you using?

**Comment by bugatsinho** [comment]
i updated to the 0.17.379 version and it is fine now!
