### ISSUE TITLE
M3u issues

### ISSUE THREAD

**Issue by alikrayim** [primaeval/script.tvguide.fullscreen#119]
I have live tv channels in m3u. File and i use vlc player to watch but still have problem it keeps moving on to next channel i dont know why, can u help?

**Comment by primaeval** [comment]
You are blocked from watching that channel.
If the stream has a special protocol with headers after an | only Kodi will play it.

**Comment by alikrayim** [comment]
No you didnt get it, i can watch all the channels in the list but it keeps changing
Like someone who change the channel to watch another one

**Comment by primaeval** [comment]
I have no idea then.
