### ISSUE TITLE
Feature: channel Listings view

### ISSUE THREAD

**Issue by primaeval** [primaeval/script.tvguide.fullscreen#30]
List view of all programs for a channel.
Highlight current channel, reminders.
Grey out past programs.
Select to open context menu to add reminders etc.

**Comment by primaeval** [comment]
added with simple select dialog
could do with a custom dialog

**Comment by iainsmacleod** [comment]
0.0.083 was consistently starting OTA channels from HDHomerun with a black
screen. FYI
