### ISSUE TITLE
Quick EPG remains on screen with main EPG.

### ISSUE THREAD

**Issue by iainsmacleod** [primaeval/script.tvguide.fullscreen#35]
If I stop the playback while viewing the quick EPG, the quick EPG remains on screen

**Comment by primaeval** [comment]
I think that was intended. Quick EPG is an alternative to EPG. Maybe it needs a Setting.

**Comment by iainsmacleod** [comment]
I think it should probably close, much like the Up Next notification, when closing playback and viewing the main screen. But let me know if you want to keep it as is for the moment.

**Comment by primaeval** [comment]
Let's see what @im85288 intended.

**Comment by im85288** [comment]
Yeah it's a bug, not something I had thought off. I agree it should be closed when playback is stopped.

**Comment by primaeval** [comment]
This should do it don't you think?
https://github.com/primaeval/script.tvguide.fullscreen/commit/f00994b4b156eb4e9da2b611de4445c6e635577a

**Comment by iainsmacleod** [comment]
Thanks
