### ISSUE TITLE
Change log never populates

### ISSUE THREAD

**Issue by iainsmacleod** [primaeval/script.tvguide.fullscreen#44]
Is there some way we can get the change log to work in Kodi - would be great to see a history of changes. Thanks

**Comment by primaeval** [comment]
It works ok for me in Jarvis.
Kodi \ Programs \ TV Guide Fullscreen \ Addon Information \ Changelog

**Comment by iainsmacleod** [comment]
so strange, I don't see it on any of my 3 systems, two Pi's and one windows.

**Comment by primaeval** [comment]
What Kodi version?

**Comment by iainsmacleod** [comment]
17.0 Alpha 3 on Windows.
LibreELEC (Krypton) v7.90.004 ALPHA on Pi

**Comment by primaeval** [comment]
Krypton is too flakey for me. It is not even close to stable. 
I never know whether I am debugging my addons or Krypton.
I recommend staying away if you are doing dev work and value your sanity. ;)

**Comment by iainsmacleod** [comment]
Oh man, I am all about the new UI. I'll upgrade to the Beta - see if that helps. Actually, I don't see changelogs for any addon...

**Comment by primaeval** [comment]
I hate Estuary. There is so much wasted space. All the commands are in the wrong place and the textures are missing or all over the place. I think this could be a Windows Vista moment in the history of Kodi.

**Comment by iainsmacleod** [comment]
For me, estuary finally has the basic widgets required. I used to use Conq.

**Comment by primaeval** [comment]
You need to set up Jarvis in portable mode on a normal computer if you want to do addon development.
You can set up a portable Krypton too to compare the bugs.
It really is too much for me to try to help fix the bugs in this addon in Krypton.
