### ISSUE TITLE
Crash when pressing INFO

### ISSUE THREAD

**Issue by im85288** [primaeval/script.tvguide.fullscreen#49]
`17:59:51 T:140540859381504   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'channel'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.tvguide.fullscreen/gui.py", line 362, in onAction
                                                self.onActionEPGMode(action)
                                              File "/storage/.kodi/addons/script.tvguide.fullscreen/gui.py", line 541, in onActionEPGMode
                                                self.showListing(program.channel)
                                            AttributeError: 'NoneType' object has no attribute 'channel'`

The strange thing here was I was pressing INFO when in TV Mode so not sure how it get's to being called in the epgmode as above. Perhaps changing showListings to only work with remote1 instead of info may help

**Comment by primaeval** [comment]
Info in epg mode is just my first guess for a spare key. Change it if you like.
All the numbers up to 6 are taken so far. Leave 7 for a future recording List if that becomes possible.

**Comment by im85288** [comment]
It's fine for me, the bigger problem is why it was called when I pressed INFO in TV Mode.

Regardless I fixed the code to not crash which is in my latest PR

**Comment by im85288** [comment]
Just for confirmation:

`action.getId() in [ACTION_SHOW_INFO,REMOTE_1]:`

So it is already using remote number 1 and the info button.

**Comment by primaeval** [comment]
There seem to be a lot of default remote mappings going on in some devices that are difficult to track down.
I spent a lot of time with someone with a FireTV that had doubled page down messages because Android had already mapped it to the media keys before Kodi.
