### ISSUE TITLE
Enter re-initiates playback

### ISSUE THREAD

**Issue by iainsmacleod** [primaeval/script.tvguide.fullscreen#52]
It appears that when I press enter to try and clear the OSD on Windows, the playback is restartd, the pop-up is displayed again.

I do not know if this is intentional behavior  for enter - but wanted to report.

**Comment by primaeval** [comment]
Enter clears the Last Channel Window but plays whatever channel is showing in the OSD.
Enter in Last Channel should really be changed to Back or Esc.

**Comment by primaeval** [comment]
Actually Enter in Last Channel should play the last channel too.

**Comment by iainsmacleod** [comment]
Ahhhhhh, ok. I am not sure if I like that behavior - I would think it should clear the info screen. I would expect it to only start playback on quick EPG and EPG.

You tell me what you want to stick with, but it seems counter-intuitive from keyboard stance.

**Comment by primaeval** [comment]
Just checked the code. It seems right.
Enter or Ok or Select to play.
Back to get back to the epg main window.
Info to load the osd and info to get rid of it, also the last channel window.
Up/down to bring up the quick epg.
Left/right to bring up last channel and get rid of it.
Seems consistent and logical enough to me, especially with some of the very limited remotes around these days like the AppleTV and FireTV.

**Comment by iainsmacleod** [comment]
Ok.
