### ISSUE TITLE
Tab result in loss of UI control

### ISSUE THREAD

**Issue by iainsmacleod** [primaeval/script.tvguide.fullscreen#53]
If I watch content, and press up I get the quick EPG. If I tab to see EPG and then tab to get back to the display - I lose quick EPG functionality. I am seeing playback info wrt progress.

**Comment by primaeval** [comment]
Tab toggles Kodi fullscreen mode.
If you have osd mode enabled in the settings, playback is actually started in a window within the TV Guide.
The osd, quick epg, last channel etc are still just windows and overlays within TV Guide.
When you press tab (fullscreen) you have actually jumped out of TV Guide into a normal Kodi video playback window.
When you press tab again you start the TV Guide up again. I think the onInit method triggers again.
I did tons of debugging today and I think that is what happens.

**Comment by iainsmacleod** [comment]
So I should always test using back to get to EPG. If so we can close this
issue.

**Comment by primaeval** [comment]
Yes.
