### ISSUE TITLE
Can get EPG and Quick EPG to display similtaneously

### ISSUE THREAD

**Issue by iainsmacleod** [primaeval/script.tvguide.fullscreen#54]
If I watch content, press Back on keyboard, then press up - I now have Quick EPG overlaying EPG.

**Comment by primaeval** [comment]
That's a bug.

**Comment by primaeval** [comment]
How quickly did you press back after playback?
There is a timeout on the osd when changing channels

**Comment by iainsmacleod** [comment]
While OSD is on. I did a few tests. Sometimes I can get the focus to remain
on Info although the EPG is there too - in which case I don't navigate EPG
(not Quick EPG) I navigate up/down in OSD.

**Comment by primaeval** [comment]
Try my latest master branch.
It should fix the osd remaining in epg mode if you press a key soon after changing channels.
It also enables the context menu while playing by moving the back button to go back to playing.
I don't know whether this should stay as it will confuse people. 
You can see the changes here to see if it makes sense:
https://github.com/primaeval/script.tvguide.fullscreen/commit/fc1edcfc08048ddb4d41ffc3b5fb8ce2dda127c5

**Comment by iainsmacleod** [comment]
OK, Still some issues here. FOr example:

Playback channel and immediately hit back - I get to browse up/down in the info tab - not the EPG (EPG and Info displayed). Wait for Info to disappear then I get the quick EPG on up and down.

Similar issue when switching to last channel, immediately hitting backsapce.

**Comment by iainsmacleod** [comment]
In general though I tested a buck of the commands, and it seems pretty solid.

**Comment by primaeval** [comment]
When playback starts it goes into osd mode for at least 3 seconds before doing the Playback Timeout countdown. Anything less is hard to read and annoying.
As soon as it detects playing media it closes the osd.
If it times out it goes back to the main epg.

This lets you see what channel is about to play and gives a window to add an error message if no stream is detected. A blank black screen doesn't give much feedback.

I don't know if this should be the final way to do this but it needs some kind of feedback to show a positive or negative channel change.

**Comment by primaeval** [comment]
I'll take out the osd on channel change in 0.0.99 and see if it makes more sense.

**Comment by iainsmacleod** [comment]
If you want something there, can we not display a header with the
information that will not have any control actions (up, down, left, right).
Or even the OSD without those control, maybe they all make it close.

**Comment by primaeval** [comment]
I tried without the osd and it didn't work. There has to be some window mode there for failed streams.
I didn't want to create another mode but I think that might be the only way to do it.

**Comment by primaeval** [comment]
I added a flag to not close the osd if the direction buttons have been pressed.
