### ISSUE TITLE
Cannot reach contect menu when playing content

### ISSUE THREAD

**Issue by iainsmacleod** [primaeval/script.tvguide.fullscreen#55]
If I press Backspace to get to EPG and I hit C for context menu - EPG disappears and I go back to the main screen. There is noway I can work out to reach context menu while having content playing in the background.

**Comment by primaeval** [comment]
That is still the original TV Guide behaviour. 
It has been niggling me all the time but there have been worse bugs to deal with.
At the moment you have to press stop to get to the context menu or go through one of the Listings views.

**Comment by iainsmacleod** [comment]
That's a bad one. Let's leave this open, because I can see wanting to set a
reminder or autoplay when viewing something else.

**Comment by primaeval** [comment]
Maybe context should always get to the menu.
Then there needs to be another key to get back to playing. Probably Play or Info.
The trouble is everyone knows that it is C in TV Guide and all the forks.

**Comment by iainsmacleod** [comment]
You can't have c work on actual playback though, would be relevant. C to
open and class would be good everywhere else - other than channel selection
screen.
