### ISSUE TITLE
Playback stops

### ISSUE THREAD

**Issue by iainsmacleod** [primaeval/script.tvguide.fullscreen#56]
If I start playback, go back to EPG, hit C to look at menu - then choose stream setup (I will have PIP picture in corner, looking at changing layout). If I press escape to stop what I am doing, playback stops - this is unexpected.

**Comment by primaeval** [comment]
I spotted that too earlier. I think it should either stop playback on entering and exiting the dialog or neither.
Usually that window is for a preview of the channel that you want to audition.

Now that it can popup while playback is going on it is probably best not to stop playing on exit.

What do you think?

**Comment by iainsmacleod** [comment]
I think you keep playback, because then you can just setup your add-ons etc
and go back to watching TV. I don't think you should ever stop playback
unless you press stop or x.

**Comment by primaeval** [comment]
Ok. Changed to keep playing in 0.0.99
