### ISSUE TITLE
Automatic channel setup issue

### ISSUE THREAD

**Issue by iainsmacleod** [primaeval/script.tvguide.fullscreen#74]
If I choose BBC and I get the popup to allow me to select which BBC2 addon I want to use - if I press cancel it looks as though it is showing BBC OSD info, so I have to press escape again to get back to the main EPG.

Happen on Krypton and Jarvis.

**Comment by primaeval** [comment]
That is a bug. I haven't fixed it yet because there were lots more. ;)
