### ISSUE TITLE
Fully exit OSD for best Video playback quality

### ISSUE THREAD

**Issue by Mike-KL** [primaeval/script.tvguide.fullscreen#77]
Ref attached post and my reply etc, I have noticed (on Rpi2 using Nightly Krypton) of need to use tab key on keyboard in order to "fully correctly?" exit osd when streaming a channel to ensure best quailty video playback in kodi.

http://forum.kodi.tv/showthread.php?tid=289523&pid=2418646#pid2418646

Once tab key has been utilised, I am still able to re-enter OSD correctly with back key with need to hit tab key to fully exit OSD again when required. (Using o key to see video playback settings is obvious clue to being fully in/out of TV Guide OSD etc)

Also notice display playback improvements are maintained when back under OSD capture loop after inital tab out and the back into OSD which is never present at first entry into TV guide add-on and selection of Channel for playback?

Thought useful to record topic as issue here that may/could be improved at some point.

---edit---

Following is debug log where I have gone into addon, then selected a channel, then used tab to step out of OSD capture loop, use o key to enter Kodi playback info,  back to re-enter TV Guide OSD, bring up quick guide, step out of osd, use o key to enter kodi playback info, back to re-enter TV Guide, stop playback, then exit Guide etc https://gist.github.com/Mike-KL/329ad485e0f57ef8f2debb6ff8120bcf

**Comment by primaeval** [comment]
The difference to Kodi is that it is playing video in a window when you go into the TV Guide Fullscreen tv mode, although the video window is actually the size of the screen. There is probably better optimisation for video in true fullscreen mode without the OSD.
The calls are to PlayMedia(). If there is a 1 as the last argument it is in windowed mode. See here:
https://github.com/primaeval/script.tvguide.fullscreen/blob/1f9efef46996be7592665bf3460af57b630cb5bd/gui.py#L1246
and here for a brief explanation of PlayMedia
http://kodi.wiki/view/List_of_built-in_functions
