### ISSUE TITLE
Dark footer

### ISSUE THREAD

**Issue by primaeval** [primaeval/script.tvguide.fullscreen#78]
@iainsmacleod  Could you have a look at tidying up the Dark skin footer when you get the time: control 4602.
This is the code in gui.py that sets its position and height to match up with the bottom of the epg rows.
https://github.com/primaeval/script.tvguide.fullscreen/blob/1f9efef46996be7592665bf3460af57b630cb5bd/gui.py#L1661
![dark footer2](https://cloud.githubusercontent.com/assets/11716348/19012759/b3a60522-87be-11e6-829a-e2b5ce455d12.PNG)
![dark footer](https://cloud.githubusercontent.com/assets/11716348/19012760/b3aa713e-87be-11e6-92d4-dc202d968cc4.PNG)

**Comment by iainsmacleod** [comment]
Was this meant to be directed at me, and if so - how would you like this to
work? I mean you want to pull the info up ot the bottom, thus making the
whole footer have to be dynamic - or did you want to fill the dead space
over a certain size with an additional "empty" program space?

**Comment by primaeval** [comment]
It is confusing when you are both called Iain. Sorry.

Have a look at how it works in the Default skin and the gui.py link in the first post. The texture 4602 C_MAIN_FOOTER is resized and its top is moved to fit the footer section.

**Comment by im85288** [comment]
I'm Ian without the I in the middle! But yeah I can imagine it's quite confusing as we are both have similar last names too! Hope everyone's doing well

**Comment by iainsmacleod** [comment]
Should be fixed now, it appears that you reference a setting based on the
default skin, so I had to put a bunch of offsets.

Also, Ian - I'm doing well. Where are you from, Scottish heritage?

**Comment by primaeval** [comment]
Thanks.
Hi Ian. Mainly fine. How are you.

**Comment by iainsmacleod** [comment]
This can be closed, right?

**Comment by primaeval** [comment]
If you are happy with it. Thanks.
