### ISSUE TITLE
Locks-ups on exit with unnecessary re-load of guide

### ISSUE THREAD

**Issue by Mike-KL** [primaeval/script.tvguide.fullscreen#91]
As per recent my and other comments http://forum.kodi.tv/showthread.php?tid=282157&pid=2518161#pid2518161

TV Guide is locking up when channel playback is stopped and users are returned to guide interface.  entering and Navigating guide without starting a channel and then backing out of the guide appears unaffected. (Has bug been introduced in last two/three updates?)

**Comment by primaeval** [comment]
Have you got something in the log I can look at?

**Comment by Mike-KL** [comment]
@primaeval apologies for not responding and providing normal log, family visiting so no time to perform check and capture a small debug log.  Anyway seems to be fine now in 0.0.313 so will close this issue.  Thanks for your continuing efforts and support with this needed add-on.

I am currently using add-on on rpi2 with milhouse Nightly builds of LibreELEC Kodi 18 Leia ;-)
