### ISSUE TITLE
skin white_snow

### ISSUE THREAD

**Issue by tycoo** [primaeval/script.tvguide.fullscreen#93]
Have a look. New white skin preview. Gonna push all the changes soon.

https://github.com/tycoo/script.tvguide.fullscreen/commit/4ef2b073ee726d72ed74bbfb51e0b8ee1480e5e5

**Comment by tycoo** [comment]
everything is up now. I splitted all the changes into several commits, so it might be easier for you to track:
https://github.com/tycoo/script.tvguide.fullscreen/commits/white_snow

There are many changes in the gui too, but with some good improvements imo.

Tommorow i am going to write down and explain the major usability and design benefits i had in mind, but no its time for bed. ;)

cya

**Comment by primaeval** [comment]
I'm trying to work out a plugin mechanism for skins so they can be installed separately.
There are a few recent messages about it on the forum.
Have you got any ideas on that?

**Comment by tycoo** [comment]
allright i tested the the new repo and installing kjb85's skin went well.

I also prepared a zip following your suggestions:
https://github.com/tycoo/script.tvguide.fullscreen/commit/7a1188a21402e84cc2e419de8ce2010a811f680d

Further i fixed a very smal issue and rebased my branch on top of your latest changes.

Now let me explain what i have done to the gui (First of all, best way to understand would be to pick my version and skin and test it).

There are lets say 4 major changes:
A new Menu bar, a new PopupMenu aka ContextMenu, many new controls and buttons and a new handling of opening and closing windows in video mode.

1. the MenuBar acts exactly as the ActionBar.  But my major issue with the action bar was, that it doesnt has the capabilites to change the size and look of the buttons. Every button has its own nonfocus & focus *.png in my skin now. 
Further i transfered some of the functions into the Menubar , which were located in the PopupMenu before. So the lists (autoplay, remind,..) and category. In view of the usability it makes more sense imo, to have easy access to this functions from the main epg screen. Especially when using a mouse.
Likewise disabling these Functions in the PopupMenu you gain more space there, which makes it possible to move its function from a setup based PopupMenu to a program info based PopupMenu at first.

2.  Following this idea i also moved the SetupFuntions (addstream, addsaltstream, streamsetup & channelsetup) to an extra window, called PopupSetup. Once all channel are set up, you need these functions only marginally. More important imo is to have a nice big program info window, with the possibilities of quick searching for extended info, websearch, set autoplaywith, autoplay, reminders, etc. So the PopupSetup Window is hidden by default but automatically opens up, when theres is no stream available.

3. Beside many new controls & buttons for the PopupMenu, like nextprograminfo, nextprogramtime, visible and invisible buttons and controls for channel & program info switching, i have added some more to the osd & quick epg too, so that almost everything could be easy accessed, with mouse, keyboard or remote.
I am thinking about to add a help ? button, which shows up the invisible buttons and some explanations.
For example on top of the PopupMenu program description i placed some invisible navigation buttons similar like in the MainEpgView.

4. At last i changed the gui, not to redraw the epg everytime after closing a window, like quickepg, osd, lastchannel and PopupMenu in VideoMode. I think this needs no further explanation why this is usefull.

As said  before, best would be to test the skin on your own, and see if i can convice you with my approach. Next step of course, would be to do many changes to your default and other skins too. I can help yout out if you like. Just take your time, think about it and big thx again for bringing this addon so far and your ongoing development.

**Comment by primaeval** [comment]
There are a lot of changes there and some good ideas. It looks very professional.
I don't like that it has broken the functionality that is there already. Quite a few people have made their own custom skins and I don't want to force them to learn how to make such big changes.
I don't mind if you add in a new menu or two but don't break the old ones. 
That is why there are 3 ways to get to the Categories. 
If you can find a way to not break the old menus I'll add it in.
I treat this as an experimental product where lots of new ideas are allowed. If it were ever going to be mass released I would trim out most of the experimental or confusing features.

I'll have a look at the code in detail but as you say it may take a bit of time.

**Comment by tycoo** [comment]
Hej, i did as requested and reworked my changes, so that both version & controls can exist side by side.
I did it easy & quick, it doesn't look elegant, on the contrary it gets more confusing, but it works ;)

https://github.com/tycoo/script.tvguide.fullscreen/commits/white_snow_rework

I tested them with your default and catbar skin, can't detect any issues so far. Except Kodi Log shows a lot of "ERROR: EXCEPTION: Non-Existent Control", because the new controls are missing of course. :( But this doesn't harm the functionality.

It will not work with kjb85's skin sadly. I had a look into his xml and some things needs to be patched. At least kjb85 has to get rid of this:  # control type="group" id="7000" # Thats the control for the catmenu background, and as correctly seen in your xml, should be an "image" control type.

**Comment by primaeval** [comment]
Thanks. I'll try it out. Quite a few people like the Blue skin and kjb85's is a better version of that as it has the catbar in it.

**Comment by tycoo** [comment]
Yup, i checked kjb85's skin again. Its just the id="7000" in line 2035 which has to be moved to line 297 and the epg will load again.

Edit: In script-tvguide-main.xml

**Comment by primaeval** [comment]
I must be tired I can't see where to put it on line 297. Could you post the fix.

**Comment by tycoo** [comment]
behind the   control type="image"
above  description>categories background</description

**Comment by primaeval** [comment]
Got it. Thanks. 
From a quick check it looks like your new changes don't break any of the other skins. I'll have a look in detail tomorrow or so as there are a lot of changes. 
How do you want to release this? As an addon in my repo or your own or something else? I really want to unbundle the skins from the addon if possible as it can take a long time to update when I make a series of code changes and inevitable fixes. ;)

**Comment by tycoo** [comment]
I would appreciate it if you like to share it in your repo as an addon.  I think this way to handle the skins is a good solution.

**Comment by tycoo** [comment]
Mission accomplished. :) For now...
