### ISSUE TITLE
Catchup Channel is always shown

### ISSUE THREAD

**Issue by tycoo** [primaeval/script.tvguide.fullscreen#95]
regardless if it is disabled in settings? ;/

**Comment by primaeval** [comment]
Visibility should be set by the Setting. Does it go away with a Settings\Source\Reset On Start?
https://github.com/primaeval/script.tvguide.fullscreen/blob/919f93b87d887f16d173eeb6d2f14704670ee154/source.py#L354

**Comment by tycoo** [comment]
yes, a reset solved it. ;) thx
